SELECT * FROM PRODUCT;
SELECT * FROM STOCK;
SELECT * FROM PRODORDER;
SELECT * FROM STORE; 
SELECT 'PD' || PDSEQ.NEXTVAL AS SEQ FROM DUAL;
----------------------------------
-- 본사/매장 재고 조회(자재코드별로 최근일자의 자재수량 조회)
SELECT p.*, s.stockDate, s.REMAINAMOUNT, s.FRREGINUM 
FROM PRODUCT p, STOCK s
WHERE p.PRODUCTNUM = s.PRODUCTNUM
AND s.FRREGINUM = '9999999999'
AND (s.PRODUCTNUM, s.STOCKDATE) IN (
    SELECT PRODUCTNUM, MAX(STOCKDATE)
    FROM STOCK
    WHERE FRREGINUM = '9999999999'
    GROUP BY PRODUCTNUM
)
AND s.stockDate LIKE '%'|| to_date('','YYYY-MM-DD')||'%'
AND p.productNum LIKE '%'||''||'%'
AND category LIKE '%'||''||'%'
AND productName LIKE '%'||''||'%'
AND opposite LIKE '%'||''||'%';
-- 본사/매장 재고 상세 페이지
SELECT *
FROM PRODUCT
WHERE productNum like '%'||''||'%';
-- 본사/매장 재고 관리 조회
SELECT s.STOCKDATE ,p.PRODUCTNUM ,p.PRODUCTNAME ,p.PRICE ,s.APPLYAMOUNT ,s.REMAINAMOUNT 
FROM PRODUCT p, STOCK s
WHERE p.PRODUCTNUM = s.PRODUCTNUM
AND s.FrRegiNum = '1234567890';
-- 매장 재고 매출내역등록
INSERT INTO STOCK 
VALUES ('PD10002', '1234567890', sysdate, -3, 
        (SELECT REMAINAMOUNT -3 
         FROM STOCK 
         WHERE PRODUCTNUM = 'PD10002' 
         AND STOCKDATE = (SELECT MAX(STOCKDATE) 
         		FROM STOCK WHERE PRODUCTNUM = 'PD10002')), null);
-- 매장 재고 관리 수정
UPDATE STOCK 
SET APPLYAMOUNT = -2,
    REMAINAMOUNT = (
        SELECT REMAINAMOUNT -2 - APPLYAMOUNT 
        FROM (
            SELECT REMAINAMOUNT, ROW_NUMBER() OVER (ORDER BY STOCKDATE DESC) AS RN 
            FROM STOCK 
            WHERE PRODUCTNUM = 'PD10002'
        ) T 
        WHERE RN = 1
    )
WHERE PRODUCTNUM = 'PD10002' AND STOCKDATE = (SELECT MAX(STOCKDATE) FROM STOCK WHERE PRODUCTNUM = 'PD10002');
-- 매장 재고 관리 삭제
DELETE FROM STOCK 
WHERE PRODUCTNUM = 'PD10002' 
AND APPLYAMOUNT = 3 
AND REMAINAMOUNT = 44;
-- 본사 재고 등록
INSERT INTO PRODUCT VALUES ('PD'||pdSeq.nextval, '', '', '', '', '', '');
INSERT INTO STOCK VALUES (#{productnum},'9999999999',sysdate,0,0,NULL);
INSERT INTO STOCK VALUES ('PD10065','9999999999',sysdate,0,0,NULL);
-- 본사 재고 수정
UPDATE PRODUCT 
SET REMARK  = ''
WHERE PRODUCTNUM = 'PD10001';
--직원스케줄캘린더 등록
INSERT INTO CLERKSCHEDULE values('2023-03-02T12:00:00','2023-03-02T18:00:00','12345678911001','1234567891');
--직원스케줄캘린더
SELECT * FROM clerkSchedule;
SELECT * FROM storeClerk;
SELECT * FROM store;
SELECT c.*, clerkname 
FROM CLERKSCHEDULE c ,STORECLERK s 
WHERE c.CLERKNUM = s.CLERKNUM 
AND c.FRREGINUM = s.FRREGINUM ;
DELETE FROM CLERKSCHEDULE 
WHERE ONDAY =''
AND CLERKNUM ='';
--매장 점검일 배정 
SELECT * FROM STORE;
SELECT * FROM EMP;
SELECT * FROM QA;
SELECT * FROM QACHECKLIST;

INSERT INTO QA VALUES('QA'||to_char(to_date('20230222', 'YYMMDD'), 'YYMMDD'), 
'1234567891','1001','N', (SELECT empnum FROM store WHERE frreginum='1234567891'), 
to_date('20230222', 'YYMMDD'),NULL,NULL); --항목추가

INSERT INTO QA
SELECT 'QA'||to_char(to_date('20230316', 'YYMMDD'), 'YYMMDD'),
QANUM_SEQ.nextval,'N', empnum, to_date('20230316', 'YYMMDD'),NULL,NULL
FROM store
WHERE frreginum='1234567890'
AND EXISTS (SELECT 1 FROM QACHECKLIST WHERE usable = 'A');

SELECT e.EMPNUM, e.ENAME, s.FRNAME
FROM STORE s, EMP e
WHERE s.EMPNUM = e.EMPNUM
AND e.ENAME IS NOT NULL;

DELETE FROM CLERKSCHEDULE
WHERE CLERKNUM IN (
  SELECT c.CLERKNUM
  FROM CLERKSCHEDULE c, STORECLERK s
  WHERE c.CLERKNUM = s.CLERKNUM
  AND c.ONDAY = #{onDay}
  AND s.clerkName = #{clerkName}
);


SELECT * FROM 
(SELECT rownum cnt , a.* FROM 
(SELECT s.STOCKDATE ,p.category ,p.PRODUCTNUM ,p.PRODUCTNAME ,
	p.PRICE ,s.APPLYAMOUNT ,s.REMAINAMOUNT, s.remark
FROM PRODUCT p, STOCK s
WHERE p.PRODUCTNUM = s.PRODUCTNUM
AND s.FrRegiNum = '1234567890'
AND p.productNum LIKE '%'||upper('pd10001')||'%'
ORDER BY s.STOCKDATE DESC) a )
WHERE cnt BETWEEN 1 AND 5;



SELECT count(*)
FROM PRODUCT p, STOCK s
WHERE p.PRODUCTNUM = s.PRODUCTNUM
AND s.FrRegiNum = '1234567890'
AND p.productNum LIKE '%'||upper('')||'%';


SELECT * FROM STOCK s ;
INSERT ALL
	INTO PRODUCT (PRODUCTNUM, CATEGORY, PRODUCTNAME, OPPOSITE, PRICE, IMG, REMARK)
		VALUES ('PD'||FERD.PDSEQ.CURRVAL, #{category}, #{productName}, #{opposite}, #{price}, #{img}, #{remark})
	INTO STOCK (PRODUCTNUM, FRREGINUM, STOCKDATE, APPLYAMOUNT, REMAINAMOUNT, REMARK)
		VALUES ('PD'||FERD.PDSEQ.CURRVAL, '9999999999', SYSDATE, 0, 0, NULL)
	SELECT * FROM DUAL;